### ISSUE TITLE
[BUG] sklearn based models

### ISSUE THREAD

**Issue by SFal76** [MohammadForouhesh/tracking-policy-agendas#8]
sklearn based models dont work, here is the output:

```
Traceback (most recent call last):
  File "/home/nothing/nlp_test/tracking-policy-agendas/main.py", line 40, in <module>
    main(emb_df, df, 'snr')
  File "/home//nothing/nlp_test//tracking-policy-agendas/main.py", line 21, in main
    pa = PAClf(text_array=dataframe.prep_text, labels=dataframe.label, embedding_doc=embedding_frame.prep_text)
  File "/home//nothing/nlp_test//tracking-policy-agendas/tracking_policy_agendas/classifiers/pa_clf.py", line 18, in __init__
    super().__init__(classifier_instance=PassiveAggressiveClassifier(max_iter=1000, loss='squared_hinge'), **kwargs)
  File "/home//nothing/nlp_test//tracking-policy-agendas/tracking_policy_agendas/classifiers/meta_sklearn_clf.py", line 20, in __init__
    if kwargs['load_path'] is not None: self.load_model(kwargs['load_path'])
KeyError: 'load_path'
```

**Comment by MohammadForouhesh** [comment]
it is fixed at #9
